// @ts-nocheck
import type { Contact, Conversation, Message, User } from "./types";

export type TemplateDemoData = {
	user: User;
	contacts: Contact[];
	conversations: Conversation[];
	messages: Message[];
};

export function createTemplateDemoData(now = Date.now()): TemplateDemoData {
	const user: User = {
		id: "template-user-dogxi",
		identityLabel: "ID",
		identityValue: "26113",
		username: "dogxi",
		displayName: "Dogxi",
		avatarUrl: "https://avatars.githubusercontent.com/dogxii?s=240",
		kind: "human",
	};

	const jerry: User = {
		id: "template-user-jerry",
		identityLabel: "ID",
		identityValue: "89713",
		username: "jerryplusy",
		displayName: "Jerry",
		avatarUrl: "https://avatars.githubusercontent.com/Jerryplusy?s=240",
		kind: "human",
	};

	const dogBot: User = {
		id: "template-bot-dog-manager",
		identityLabel: "ID",
		identityValue: "12477",
		username: "dog_bot",
		displayName: "狗管家",
		avatarUrl: "https://avatars.githubusercontent.com/verxis?s=240",
		kind: "bot",
	};

	const viki: User = {
		id: "template-user-viki",
		identityLabel: "ID",
		identityValue: "40173",
		username: "vikiboss",
		displayName: "Viki",
		avatarUrl: "https://avatars.githubusercontent.com/vikiboss?s=240",
		kind: "human",
	};

	const contacts: Contact[] = [
		{ ...jerry, createdAt: iso(now - 12_600_000) },
		{ ...viki, createdAt: iso(now - 15_800_000) },
		{ ...dogBot, createdAt: iso(now - 7_200_000) },
	];

	return {
		user,
		contacts,
		conversations: [
			{
				id: "template-conv-dog-king-group",
				type: "group",
				updatedAt: iso(now - 60_000),
				otherUser: null,
				group: {
					id: "template-group-dog-king",
					name: "狗大王的群聊",
					identityLabel: "群号",
					identityValue: "58201",
					avatarUrl: "https://cdn.jsdmirror.com/gh/dogxii/face/avatar.jpg",
					announcement: "呱呱呱呱",
					memberCount: 4,
					role: "owner",
				},
				members: [
					{
						...user,
						role: "owner",
						joinedAt: iso(now - 86_400_000),
					},
					{
						...jerry,
						role: "admin",
						joinedAt: iso(now - 82_000_000),
					},
					{
						...dogBot,
						role: "member",
						joinedAt: iso(now - 72_000_000),
					},
					{
						...viki,
						role: "member",
						joinedAt: iso(now - 68_000_000),
					},
				],
				unreadCount: 3,
				preference: {
					pinned: false,
					muted: false,
					blocked: false,
				},
				lastMessage: {
					id: "template-group-m24",
					senderId: jerry.id,
					senderDisplayName: jerry.displayName,
					body: "@Dogxi 你好",
					createdAt: iso(now - 60_000),
				},
			},
			{
				id: "template-conv-dog-bot",
				type: "direct",
				updatedAt: iso(now - 180_000),
				otherUser: dogBot,
				group: null,
				members: [],
				unreadCount: 1,
				preference: {
					pinned: false,
					muted: false,
					blocked: false,
				},
				lastMessage: {
					id: "template-bot-m8",
					senderId: dogBot.id,
					body: "Hi Dogxi, I received: [敷敷:17]",
					createdAt: iso(now - 180_000),
				},
			},
			{
				id: "template-conv-jerry",
				type: "direct",
				updatedAt: iso(now - 420_000),
				otherUser: jerry,
				group: null,
				members: [],
				preference: {
					pinned: false,
					muted: false,
					blocked: false,
				},
				lastMessage: {
					id: "template-jerry-m6",
					senderId: jerry.id,
					body: "在吗在吗",
					createdAt: iso(now - 420_000),
				},
			},
			{
				id: "template-conv-viki",
				type: "direct",
				updatedAt: iso(now - 780_000),
				otherUser: viki,
				group: null,
				members: [],
				preference: {
					pinned: false,
					muted: true,
					blocked: false,
				},
				lastMessage: {
					id: "template-viki-m6",
					senderId: user.id,
					body: "推送消息！",
					createdAt: iso(now - 780_000),
				},
			},
		],
		messages: [
			{
				id: "template-group-m1",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: "123",
				createdAt: iso(now - 1_980_000),
			},
			{
				id: "template-group-m2",
				conversationId: "template-conv-dog-king-group",
				senderId: jerry.id,
				sender: jerry,
				body: "有没有人",
				createdAt: iso(now - 1_900_000),
			},
			{
				id: "template-group-m3",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: "[敷敷:15]",
				createdAt: iso(now - 1_820_000),
			},
			{
				id: "template-group-m4",
				conversationId: "template-conv-dog-king-group",
				senderId: viki.id,
				sender: viki,
				body: "111",
				createdAt: iso(now - 1_740_000),
			},
			{
				id: "template-group-m5",
				conversationId: "template-conv-dog-king-group",
				senderId: dogBot.id,
				sender: dogBot,
				body: "111",
				createdAt: iso(now - 1_660_000),
			},
			{
				id: "template-group-m6",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: "/ping",
				createdAt: iso(now - 1_580_000),
			},
			{
				id: "template-group-m7",
				conversationId: "template-conv-dog-king-group",
				senderId: dogBot.id,
				sender: dogBot,
				body: "pong",
				createdAt: iso(now - 1_500_000),
			},
			{
				id: "template-group-m8",
				conversationId: "template-conv-dog-king-group",
				senderId: jerry.id,
				sender: jerry,
				body: "[敷敷:1]",
				createdAt: iso(now - 1_420_000),
			},
			{
				id: "template-group-m9",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: "这是一条很长很长的消息，这是一条很长很长的消息，这是一条很长很长的消息，这是一条很长很长的消息，这是一条很长很长的消息，这是一条很长很长的消息，这是一条很长很长的消息，这是一条很长很长的消息",
				createdAt: iso(now - 1_340_000),
			},
			{
				id: "template-group-m10",
				conversationId: "template-conv-dog-king-group",
				senderId: viki.id,
				sender: viki,
				body: '```ts\nconst msg = "hello"\nexport const preview = msg\n```',
				createdAt: iso(now - 1_260_000),
			},
			{
				id: "template-group-m11",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: '```ts\nimport type { APIRoute } from "astro";\n\nimport emojisConfig from "@data/emojis.json";\nexport const prerender = true;\n\nexport const GET: APIRoute = () =>\n	new Response(JSON.stringify(emojisConfig), {\n		status: 200,\n		headers: {\n			"Content-Type": "application/json; charset=utf-8",\n			"Cache-Control": "public, max-age=3600",\n		},\n});\n```',
				createdAt: iso(now - 1_180_000),
			},
			{
				id: "template-group-m12",
				conversationId: "template-conv-dog-king-group",
				senderId: jerry.id,
				sender: jerry,
				body: "@Dogxi 艾特",
				createdAt: iso(now - 1_100_000),
			},
			{
				id: "template-group-m13",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: "收到",
				createdAt: iso(now - 1_020_000),
			},
			{
				id: "template-group-m14",
				conversationId: "template-conv-dog-king-group",
				senderId: dogBot.id,
				sender: dogBot,
				body: "message",
				createdAt: iso(now - 940_000),
			},
			{
				id: "template-group-m15",
				conversationId: "template-conv-dog-king-group",
				senderId: viki.id,
				sender: viki,
				body: "```tsx\n<div>hello</div>\n```",
				createdAt: iso(now - 860_000),
			},
			{
				id: "template-group-m16",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: "呱呱呱呱",
				createdAt: iso(now - 780_000),
			},
			{
				id: "template-group-m17",
				conversationId: "template-conv-dog-king-group",
				senderId: jerry.id,
				sender: jerry,
				body: "呱呱呱呱",
				createdAt: iso(now - 700_000),
			},

			{
				id: "template-group-m18",
				conversationId: "template-conv-dog-king-group",
				senderId: dogBot.id,
				sender: dogBot,
				body: "Hi Dogxi",
				createdAt: iso(now - 540_000),
			},
			{
				id: "template-group-m19",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: "@狗管家 你好",
				createdAt: iso(now - 460_000),
			},
			{
				id: "template-group-m20",
				conversationId: "template-conv-dog-king-group",
				senderId: dogBot.id,
				sender: dogBot,
				body: "Hi Dogxi, I received: 你好",
				createdAt: iso(now - 380_000),
			},
			{
				id: "template-group-m21",
				conversationId: "template-conv-dog-king-group",
				senderId: viki.id,
				sender: viki,
				body: "你好",
				createdAt: iso(now - 260_000),
			},
			{
				id: "template-group-m22",
				conversationId: "template-conv-dog-king-group",
				senderId: dogBot.id,
				sender: dogBot,
				body: "1",
				createdAt: iso(now - 260_000),
			},
			{
				id: "template-group-m23",
				conversationId: "template-conv-dog-king-group",
				senderId: jerry.id,
				sender: jerry,
				body: "2",
				createdAt: iso(now - 140_000),
			},
			{
				id: "template-group-m24",
				conversationId: "template-conv-dog-king-group",
				senderId: jerry.id,
				sender: jerry,
				body: "@Dogxi 你好",
				createdAt: iso(now - 60_000),
			},
			{
				id: "template-group-m25",
				conversationId: "template-conv-dog-king-group",
				senderId: dogBot.id,
				sender: dogBot,
				body: "本网站仅为 IM 前端模版演示 Demo，详情见 GitHub 仓库",
				createdAt: iso(now - 60_000),
			},
			{
				id: "template-group-m26",
				conversationId: "template-conv-dog-king-group",
				senderId: user.id,
				sender: user,
				body: "GitHub: [dogxii/webark-im-template](https://github.com/dogxii/webark-im-template)",
				createdAt: iso(now - 60_000),
			},
			{
				id: "template-group-m27",
				conversationId: "template-conv-dog-king-group",
				senderId: jerry.id,
				sender: jerry,
				body: "GitHub: [dogxii/webark-im-template](https://github.com/dogxii/webark-im-template)",
				createdAt: iso(now - 60_000),
			},
			{
				id: "template-group-m28",
				conversationId: "template-conv-dog-king-group",
				senderId: viki.id,
				sender: viki,
				body: "GitHub: [dogxii/webark-im-template](https://github.com/dogxii/webark-im-template)",
				createdAt: iso(now - 60_000),
			},
			{
				id: "template-group-m29",
				conversationId: "template-conv-dog-king-group",
				senderId: dogBot.id,
				sender: dogBot,
				body: "[敷敷:17]",
				createdAt: iso(now - 60_000),
			},
			{
				id: "template-bot-m1",
				conversationId: "template-conv-dog-bot",
				senderId: user.id,
				sender: user,
				body: "/ping",
				createdAt: iso(now - 1_100_000),
			},
			{
				id: "template-bot-m2",
				conversationId: "template-conv-dog-bot",
				senderId: dogBot.id,
				sender: dogBot,
				body: "pong",
				createdAt: iso(now - 1_020_000),
			},
			{
				id: "template-bot-m3",
				conversationId: "template-conv-dog-bot",
				senderId: user.id,
				sender: user,
				body: "/roll",
				createdAt: iso(now - 940_000),
			},
			{
				id: "template-bot-m4",
				conversationId: "template-conv-dog-bot",
				senderId: dogBot.id,
				sender: dogBot,
				body: "d6 = 5",
				createdAt: iso(now - 860_000),
			},
			{
				id: "template-bot-m5",
				conversationId: "template-conv-dog-bot",
				senderId: user.id,
				sender: user,
				body: "nihao",
				createdAt: iso(now - 500_000),
			},
			{
				id: "template-bot-m6",
				conversationId: "template-conv-dog-bot",
				senderId: dogBot.id,
				sender: dogBot,
				body: "Hi Dogxi, I received: nihao",
				createdAt: iso(now - 420_000),
			},
			{
				id: "template-bot-m7",
				conversationId: "template-conv-dog-bot",
				senderId: user.id,
				sender: user,
				body: "[敷敷:2]",
				createdAt: iso(now - 260_000),
			},
			{
				id: "template-bot-m8",
				conversationId: "template-conv-dog-bot",
				senderId: dogBot.id,
				sender: dogBot,
				body: "Hi Dogxi, I received: [敷敷:2]",
				createdAt: iso(now - 180_000),
			},
			{
				id: "template-jerry-m1",
				conversationId: "template-conv-jerry",
				senderId: jerry.id,
				sender: jerry,
				body: "111",
				createdAt: iso(now - 3_200_000),
			},
			{
				id: "template-jerry-m2",
				conversationId: "template-conv-jerry",
				senderId: user.id,
				sender: user,
				body: "123",
				createdAt: iso(now - 3_080_000),
			},
			{
				id: "template-jerry-m3",
				conversationId: "template-conv-jerry",
				senderId: jerry.id,
				sender: jerry,
				body: "nihao",
				createdAt: iso(now - 2_960_000),
			},
			{
				id: "template-jerry-m4",
				conversationId: "template-conv-jerry",
				senderId: user.id,
				sender: user,
				body: "hey",
				createdAt: iso(now - 2_840_000),
			},
			{
				id: "template-jerry-m5",
				conversationId: "template-conv-jerry",
				senderId: jerry.id,
				sender: jerry,
				body: "[敷敷:11]",
				createdAt: iso(now - 2_720_000),
			},
			{
				id: "template-jerry-m6",
				conversationId: "template-conv-jerry",
				senderId: jerry.id,
				sender: jerry,
				body: "在吗在吗",
				createdAt: iso(now - 420_000),
			},
			{
				id: "template-viki-m1",
				conversationId: "template-conv-viki",
				senderId: viki.id,
				sender: viki,
				body: "hey",
				createdAt: iso(now - 3_600_000),
			},
			{
				id: "template-viki-m2",
				conversationId: "template-conv-viki",
				senderId: user.id,
				sender: user,
				body: "123",
				createdAt: iso(now - 3_480_000),
			},
			{
				id: "template-viki-m3",
				conversationId: "template-conv-viki",
				senderId: user.id,
				sender: user,
				body: "**加粗** 和 `code`",
				createdAt: iso(now - 3_360_000),
			},
			{
				id: "template-viki-m4",
				conversationId: "template-conv-viki",
				senderId: user.id,
				sender: user,
				body: '```ts\nimport type { Message } from "./types"\n\nexport function preview(message: Message) {\n  return message.body.slice(0, 24)\n}\n```',
				createdAt: iso(now - 3_240_000),
			},
			{
				id: "template-viki-m5",
				conversationId: "template-conv-viki",
				senderId: viki.id,
				sender: viki,
				body: "[敷敷:16]",
				createdAt: iso(now - 900_000),
			},
			{
				id: "template-viki-m6",
				conversationId: "template-conv-viki",
				senderId: user.id,
				sender: user,
				body: "推送消息！",
				createdAt: iso(now - 780_000),
			},
		],
	};
}

function iso(value: number) {
	return new Date(value).toISOString();
}
